export const drawerItemsMain = [
  {
    key: 'News',
    title: 'News',
    iconName: 'newspaper-variant-outline',
    isExpandable: true,
    routes: [
      { nav: 'MainDrawer', routeName: 'BreakingNews', title: 'Breaking News' },
      { nav: 'MainDrawer', routeName: 'LatestNews', title: 'Latest News' },
      { nav: 'MainDrawer', routeName: 'NewsFeatures', title: 'News Features' },
      {
        nav: 'MainDrawer',
        routeName: 'Investigations',
        title: 'Investigations',
      },
      { nav: 'MainDrawer', routeName: 'Interviews', title: 'Interviews' },
      { nav: 'MainDrawer', routeName: 'PhotoNews', title: 'Photo News' },
      { nav: 'MainDrawer', routeName: 'SocietyNews', title: 'Society News' },
    ],
  },
  {
    key: 'Comments',
    title: 'Comments',
    iconName: 'comment-text-outline',
    isExpandable: true,
    routes: [
      { nav: 'MainDrawer', routeName: 'Editorial', title: 'Editorial' },
      {
        nav: 'MainDrawer',
        routeName: 'DrChristine',
        title: 'Dr Christine O Malley ',
      },
      { nav: 'MainDrawer', routeName: 'DrMichael', title: 'Dr Michael Conroy' },
      { nav: 'MainDrawer', routeName: 'DrMuiris', title: 'Dr Muiris Houston' },
      { nav: 'MainDrawer', routeName: 'DrPat', title: 'Dr Pat Harrold' },
      { nav: 'MainDrawer', routeName: 'GeorgeWinter', title: 'George Winter' },
      { nav: 'MainDrawer', routeName: 'DrPaddy', title: 'Dr Paddy Barrett' },
      { nav: 'MainDrawer', routeName: 'DrLucia', title: 'Dr Lucia Gannon' },
      { nav: 'MainDrawer', routeName: 'DrNeasa', title: 'Dr Neasa Conneally' },
      {
        nav: 'MainDrawer',
        routeName: 'ProfBrendan',
        title: 'Prof Brendan Kelly',
      },
      {
        nav: 'MainDrawer',
        routeName: 'ProfSeamus',
        title: 'Prof Seamus O Mahony',
      },
      { nav: 'MainDrawer', routeName: 'Letters', title: 'Letters' },
    ],
  },
  {
    key: 'Life',
    title: 'Life',
    iconName: 'heart-outline',
    isExpandable: true,
    routes: [
      { nav: 'MainDrawer', routeName: 'Conferences', title: 'Conferences' },
      { nav: 'MainDrawer', routeName: 'Finance', title: 'Finance' },
      { nav: 'MainDrawer', routeName: 'TheGander', title: 'The Gander' },
      {
        nav: 'MainDrawer',
        routeName: 'TheDorsalView',
        title: 'The Dorsal View',
      },
      { nav: 'MainDrawer', routeName: 'Sport', title: 'Sport' },
      { nav: 'MainDrawer', routeName: 'Culture', title: 'Culture' },
      { nav: 'MainDrawer', routeName: 'Motoring', title: 'Motoring' },
      { nav: 'MainDrawer', routeName: 'SportsQuiz', title: 'Sports Quiz' },
    ],
  },
  {
    key: 'NewsTeam',
    title: 'News Team',
    iconName: 'home-outline',
    isExpandable: true,
    routes: [
      {
        nav: 'MainDrawer',
        routeName: 'CatherineReilly',
        title: 'Catherine Reilly',
      },
      { nav: 'MainDrawer', routeName: 'DavidLynch', title: 'David Lynch' },
      {
        nav: 'MainDrawer',
        routeName: 'PaulMulholland',
        title: 'Paul Mulholland',
      },
      {
        nav: 'MainDrawer',
        routeName: 'PriscillaLynch',
        title: 'Priscilla Lynch',
      },
    ],
  },
  {
    key: 'Clinical',
    title: 'Clinical',
    iconName: 'home-outline',
    isExpandable: true,
    routes: [
      { nav: 'MainDrawer', routeName: 'CaseStudies', title: 'Case Studies' },
      { nav: 'MainDrawer', routeName: 'Research', title: 'Research' },
      { nav: 'MainDrawer', routeName: 'Interview', title: 'Interview' },
      { nav: 'MainDrawer', routeName: 'Feature', title: 'Feature' },
    ],
  },
  {
    key: 'Scocieties',
    title: 'Scocieties',
    iconName: 'account-group',
    isExpandable: true,
    routes: [
      { nav: 'MainDrawer', routeName: 'ISR', title: 'ISR' },
      { nav: 'MainDrawer', routeName: 'CPI', title: 'CPI' },
      { nav: 'MainDrawer', routeName: 'ITS', title: 'ITS' },
      { nav: 'MainDrawer', routeName: 'ISMO', title: 'ISMO' },
      { nav: 'MainDrawer', routeName: 'PCDSI', title: 'PCDSI' },
      { nav: 'MainDrawer', routeName: 'ISG', title: 'ISG' },
      { nav: 'MainDrawer', routeName: 'IICNINA', title: 'IICN / INA' },
      { nav: 'MainDrawer', routeName: 'IES', title: 'IES' },
      { nav: 'MainDrawer', routeName: 'ICS', title: 'ICS' },
      { nav: 'MainDrawer', routeName: 'INS', title: 'INS' },
      { nav: 'MainDrawer', routeName: 'HAI', title: 'HAI' },
    ],
  },
  {
    key: 'QuickLinks',
    title: 'Quick Links',
    iconName: 'account-group',
    isExpandable: true,
    routes: [
      { nav: 'MainDrawer', routeName: 'AboutUs', title: 'About Us' },
      {
        nav: 'MainDrawer',
        routeName: 'PrivacyPolicy',
        title: 'Privacy Policy',
      },
      { nav: 'MainDrawer', routeName: 'Terms', title: 'Terms & Conditions' },
    ],
  },
]
