export const drawerItemsMain = [
    {
      key: 'News',
      title: 'News',
      iconName: 'newspaper-variant-outline',
      isExpandable:true,
      routes: [
        {nav: 'MainDrawer', routeName: 'BreakingNews', title: 'Breaking News'},
        {nav: 'MainDrawer', routeName: 'LatestNews', title: 'Latest News'},
        {nav: 'MainDrawer', routeName: 'NewsFeatures', title: 'News Features'},
        {nav: 'MainDrawer', routeName: 'Investigations', title: 'Investigations'},
        {nav: 'MainDrawer', routeName: 'Interviews', title: 'Interviews'},
        {nav: 'MainDrawer', routeName: 'PhotoNews', title: 'Photo News'},
        {nav: 'MainDrawer', routeName: 'SocietyNews', title: 'Society News'}
    ],
    },
    {
      key: 'Comments',
      title: 'Comments',
      iconName:'comment-text-outline',
      isExpandable:true,
      routes: [
        {nav: 'MainDrawer', routeName: 'Editorial', title: 'Editorial'},
        {nav: 'MainDrawer', routeName: 'DrChristine', title: 'Dr Christine O Malley '},
        {nav: 'MainDrawer', routeName: 'DrMichael', title: 'Dr Michael Conroy'},
        {nav: 'MainDrawer', routeName: 'DrMuiris', title: 'Dr Muiris Houston'},
        {nav: 'MainDrawer', routeName: 'DrPat', title: 'Dr Pat Harrold'},
        {nav: 'MainDrawer', routeName: 'GeorgeWinter', title: 'George Winter'},
        {nav: 'MainDrawer', routeName: 'DrPaddy', title: 'Dr Paddy Barrett'},
        {nav: 'MainDrawer', routeName: 'DrLucia', title: 'Dr Lucia Gannon'},
        {nav: 'MainDrawer', routeName: 'DrNeasa', title: 'Dr Neasa Conneally'},
        {nav: 'MainDrawer', routeName: 'ProfBrendan', title: 'Prof Brendan Kelly'},
        {nav: 'MainDrawer', routeName: 'ProfSeamus', title: 'Prof Seamus O Mahony'},
        {nav: 'MainDrawer', routeName: 'Letters', title: 'Letters'},
      ],
    },
    {
      key: 'Life',
      title: 'Life',
      iconName: 'heart-outline',
      isExpandable:true,
      routes: [
        {nav: 'MainDrawer', routeName: 'Conferences', title: 'Conferences'},
        {nav: 'MainDrawer', routeName: 'Finance', title: 'Finance'},
        {nav: 'MainDrawer', routeName: 'TheGander', title: 'The Gander'},
        {nav: 'MainDrawer', routeName: 'TheDorsalView', title: 'The Dorsal View'},
        {nav: 'MainDrawer', routeName: 'Sport', title: 'Sport'},
        {nav: 'MainDrawer', routeName: 'Culture', title: 'Culture'},
        {nav: 'MainDrawer', routeName: 'Motoring', title: 'Motoring'},
        {nav: 'MainDrawer', routeName: 'SportsQuiz', title: 'Sports Quiz'},
    ],
    },
    {
      key: 'Clinical',
      title: 'Clinical',
      iconName: 'home-outline',
      isExpandable:true,
      routes: [
        {nav: 'MainDrawer', routeName: 'CaseStudies', title: 'Case Studies'},
        {nav: 'MainDrawer', routeName: 'Research', title: 'Research'},
        {nav: 'MainDrawer', routeName: 'Interview', title: 'Interview'},
        {nav: 'MainDrawer', routeName: 'Feature', title: 'Feature'},
    ],
    },
    {
      key: 'Scocieties',
      title: 'Scocieties',
      iconName: 'account-group',
      isExpandable:true,
      routes: [
        {nav: 'MainDrawer', routeName: 'ISR', title: 'ISR'},
        {nav: 'MainDrawer', routeName: 'CPI', title: 'CPI'},
        {nav: 'MainDrawer', routeName: 'ITS', title: 'ITS'},
        {nav: 'MainDrawer', routeName: 'ISMO', title: 'ISMO'},
        {nav: 'MainDrawer', routeName: 'PCDSI', title: 'PCDSI'},
        {nav: 'MainDrawer', routeName: 'ISG', title: 'ISG'},
        {nav: 'MainDrawer', routeName: 'IICNINA', title: 'IICN / INA'},
        {nav: 'MainDrawer', routeName: 'IES', title: 'IES'},
        {nav: 'MainDrawer', routeName: 'ICS', title: 'ICS'},
    ],
    },
    {
      key: 'Galleries',
      title: 'Galleries',
      iconName: 'briefcase-outline',
      isExpandable:false,
      routes: [
        {nav: 'MainDrawer', routeName: 'GalleriesScreen', title: 'Galleries'},
    ],
    },
    {
      key: 'Classifieds',
      title: 'Classifieds',
      iconName: 'doctor',
      isExpandable:true,
      routes: [
        {nav: 'MainDrawer', routeName: 'ConsultingRooms', title: 'Consulting Rooms'},
        {nav: 'MainDrawer', routeName: 'Dermatology', title: 'Dermatology'},
        {nav: 'MainDrawer', routeName: 'DoctorsWanted', title: 'Doctors Wanted'},
        {nav: 'MainDrawer', routeName: 'DoctorAvailable', title: 'Doctor Available'},
        {nav: 'MainDrawer', routeName: 'FlatsToLet', title: 'Flats To Let'},
        {nav: 'MainDrawer', routeName: 'GolfAndSports', title: 'Golf And Sports'},
        {nav: 'MainDrawer', routeName: 'HolidayResorts', title: 'Holiday Resorts'},
        {nav: 'MainDrawer', routeName: 'InternationalJobs', title: 'International Jobs'},
        {nav: 'MainDrawer', routeName: 'Languages', title: 'Languages'},
        {nav: 'MainDrawer', routeName: 'LocumAvailable', title: 'Locum Available'},
        {nav: 'MainDrawer', routeName: 'LocumRequired', title: 'Locum Required'},
        {nav: 'MainDrawer', routeName: 'MedicalEquipment', title: 'Medical Equipment'},
        {nav: 'MainDrawer', routeName: 'MedicalPractice', title: 'Medical Practice'},
        {nav: 'MainDrawer', routeName: 'MedicalSecretary', tite: 'Practice Nurse'},
        {nav: 'MainDrawer', routeName: 'Property', title: 'Property'},
        {nav: 'MainDrawer', routeName: 'Training', title: 'Training'},
        {nav: 'MainDrawer', routeName: 'Volunterring', title: 'Volunterring'},
        {nav: 'MainDrawer', routeName: 'Events', title: 'Events'},
    ],
    },
    {
      key: 'Sponsored',
      title: 'Sponsored',
      iconName: 'account-cash-outline',
      isExpandable:false,
      routes: [
        {nav: 'MainDrawer', routeName: 'SponsoredScreen', title: 'Sponsored'},
    ],
    },
    {
      key: 'Advertise',
      title: 'Advertise',
      iconName: 'account-cash-outline',
      isExpandable:false,
      routes: [
        {nav: 'MainDrawer', routeName: 'AdvertiseScreen', title: 'Advertise'},
    ],
    },
    {
      key: 'Premium',
      title: 'Premium',
      iconName: 'briefcase-outline',
      isExpandable:false,
      routes: [
        {nav: 'MainDrawer', routeName: 'PremiumScreen', title: 'Premium'},
    ],
    },
    {
      key: 'Competition',
      title: 'Competition',
      iconName: 'arm-flex-outline',
      isExpandable:false,
      routes: [
        {nav: 'MainDrawer', routeName: 'CompetitionScreen', title: 'Competition'},
    ],
    },
  ];
  
  